version: '3.8'

services:
  webapp:
    container_name: ctf-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=CTF;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    depends_on:
      - db
    volumes:
      - ./uploads:/app/wwwroot/uploads
    networks:
      - ctf-network
    

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge

volumes:
  mssql-data: